sudo: required

before_install:
  - wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
  - sudo mv catch.hpp /usr/local/include

language: cpp

compiler:
  - clang
  
script:
  - cd challenges_1 && make test && ./tests
