sudo: required

before_install: sudo wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp /usr/local/include/

language: cpp

compiler:
  - clang
  
script:
  - cd challenges_1 && make test && ./tests
